services:
  - type: web
    name: rag-agent-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: LLM_PROVIDER
        value: openai
      - key: LLM_MODEL
        value: gpt-4
      - key: LLM_API_KEY
        sync: false  # Set this in Render dashboard
      - key: LLM_BASE_URL
        value: https://api.openai.com/v1
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: ANTHROPIC_API_KEY
        sync: false  # Set this in Render dashboard if needed
    autoDeploy: false  # Set to true if you want auto-deploy from GitHub